name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-restore --output build
    - name: List out directory contents
      run: |
        echo "Listing the contents of the GitHub workspace directory"
        ls ${{ github.workspace }}
        echo "Recursively listing all contents of the current directory"
        ls -R
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build
        if-no-files-found: error
