name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-build --verbosity normal
      steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: Publish
      run: dotnet publish --no-restore --output build
    - name: List out directory contents
      run: |
        echo "Listing the contents of the GitHub workspace directory"
        ls ${{ github.workspace }}
        echo "Recursively listing all contents of the current directory"
        ls -R
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build
        if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: build
        if-no-files-found: error
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: dev-animal-vanzeyes
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: my-artifact
