# This is a basic workflow to help you get started with Actions

name: webAppDeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --no-restore --output build

      - name: artifact-upload
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: build
          if-no-files-found: error
          
          
  release:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: artifact-download
        uses: actions/download-artifact@v1
        with:
          name: my-artifact
          path: build
          if-no-files-found: error

      - name: 'Run Azure webapp deploy action using publish profile credentials' 
        uses: azure/webapps-deploy@v2 
        with:  
          app-name: dev-animal-ilovebbogle # Replace with your app name 
          publish-profile: ${{ secrets.ILOVEBBOGLE_SECRET  }} # Define secret variable in repository settings as per action documentation 
          package : build
              

 

